### ISSUE TITLE
Task #113 - Backendkomponente definieren

### ISSUE THREAD

**Issue by ebauersandoval** [SE-TINF22B2/G4-Get2Gether#114]
In Visual Paradigm soll eine neue Ansicht erstellt werden mit den detaillierteren Backendkomponenten.

**Comment by Drumber** [comment]
Aktueller Stand:

![Image](https://github.com/SE-TINF22B2/G4-Get2Gether/assets/29163322/9cb5fced-3915-4573-8046-5dc6f4587bde)
