### ISSUE TITLE
Task #113 - Gesamtüberblick überarbeiten

### ISSUE THREAD

**Issue by ebauersandoval** [SE-TINF22B2/G4-Get2Gether#116]
Das bestehende Komponentendiagramm muss nochmal final überarbeitet werden, speziell die externen Schnittstellen müssen überarbeitet werden.

**Comment by Drumber** [comment]
Aktueller Stand:

![Image](https://github.com/SE-TINF22B2/G4-Get2Gether/assets/29163322/ac411599-a981-4a9d-bd68-2b77b1108774)
