### ISSUE TITLE
Task #73 - Eventoverviewseite anlegen

### ISSUE THREAD

**Issue by ebauersandoval** [SE-TINF22B2/G4-Get2Gether#118]
### Beschreibung
Sobald man sich bei Get2Gether anmeldet landet man auf der Eventoverviewseite. Diese Seite wird angezeigt solange man kein Event ausgewählt hat.

### Aufgaben
- [ ] Komponente mit Bild und Hinweistext erstellen

### Designvorlage
Link zum Design: [Eventoverviewseite](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=307%3A2287&mode=design&t=QJ4jvbD6K5Uvq1U0-1)

**Comment by Drumber** [comment]
✅ Code-QA abgeschlossen.

Sieht gut aus! Ich habe nur das SVG Icon durch ein Material Icon ersetzt und bischen aufgeräumt.
