### ISSUE TITLE
Story #120 - Widget-Maske anlegen

### ISSUE THREAD

**Issue by ebauersandoval** [SE-TINF22B2/G4-Get2Gether#120]
### Beschreibung

**Als** Nutzer **möchte** ich mein erstelltes Event mit Widgets erweitern, **um** so die Planung des Events zu erleichtern. Mithilfe eines Buttons wird die Widget-Maske angezeigt über die man die verfügbaren Widgets auswählen und diese somit dem Event hinzufügen kann.

### Aufgaben

- [x] #121 
- [x] #122 

### Kriterien für die Abnahme

- Die Widget-Maske ist erstellt und an verschiedene Bildschirmgrößen anpassbar.
- Die Umsetzung soll auf der Figma-Designvorlage basieren.
- Die Tasks #121  und #122  sind abgeschlossen.

### Abgrenzungen
- Die Implementierung der Widgetnavigationsleiste ist nicht Teil dieser Story.

**Comment by Drumber** [comment]
✅ Code-QA abgeschlossen
