### ISSUE TITLE
Story-#125- Codecoverage tracken 

### ISSUE THREAD

**Issue by Lica200** [SE-TINF22B2/G4-Get2Gether#125]
### Beschreibung

Ziel dieser Story ist es dass Code und Pullrequests auf ihre Testabdeckung überprüft werden. Damit soll bevor gemergt wird sichergestellt werden, dass die Qualität des Codes ausreichend ist. Außerdem soll vom bestehenden Code die Testabdeckung getrackt werden können.

### Aufgaben

- [x] evaluieren der Frameworks, die sich anbieten
- [x] Einarbeitung in das Framework
- [x] Einbindung in das Projekt

### Kriterien für die Abnahme

- alle Pullrequests werden auf ihre Testabdeckung hin überprüft
- Die Testabdeckung des bestehenden Codes ist visualisiert

**Comment by Flugschnitzel** [comment]
Falls die Story durch ist, kannst du sie noch schließen
