### ISSUE TITLE
Bug #153 - Eventpage Funktionalitäten fixen

### ISSUE THREAD

**Issue by ebauersandoval** [SE-TINF22B2/G4-Get2Gether#153]
### Beschreibung

Einige Buttons haben noch keine richtige Funktionalität implementiert, diese müssen zum Teil auch im Backend erweitert werden.

### Aufgaben

- [x] Verlassen-Button eines Events
- [x] Einladungslink

**Comment by Flugschnitzel** [comment]
Abgesehen davon wäre Code QA durch
