### ISSUE TITLE
Story #5 - Design vorschlag erstellen

### ISSUE THREAD

**Issue by ebauersandoval** [SE-TINF22B2/G4-Get2Gether#5]
Die Anwendung soll ein Design-Handbuch sowie ein Mockup bekommen, um die Anwendung dementsprechend umzusetzen. Dazu gehört die Abstimmung einer Farbpalette, einer Schriftart, den Schriftgrößen, sowie Designs für alle möglichen Ansichten der Anwendung.

- [x] #25 
- [x] #26 
- [x] #28 
- [x] #29 
- [x] #30 
- [x] #31 
- [x] #32 
- [x] #33 
- [x] #34 
- [x] #35 

Design einsehbar unter:
https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=0%3A1&mode=design&t=O4fe27Rsg7kQY2UY-1

**Comment by sophiadeckhut** [comment]
https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=0%3A1&mode=design&t=O4fe27Rsg7kQY2UY-1
