### ISSUE TITLE
Story-Template

### ISSUE THREAD

**Issue by HaventSlept** [SE-TINF22B2/G4-Get2Gether#56]
**Beschreibung:**
Die Überschriften: "Beschreibung, Aufgabe und Kriterien für Abnahme", sind immer in **Bold** zu schreiben. Unter der Überschrift "Beschreibung" Steht zusammengefasst, worum es in der Story/der Task geht.

**Aufgabe:**
 [ ] Aufgaben sind immer mit einer Checkbox zu versehen
 [x] Sobald eine Aufgabe erfüllt ist ist die Checkbox abzuhaken
 [ ] Aufgaben sind für eine genaue Vorgangsbeschreibung darzustellen
 [ ] Eine Aufgabe beinhaltet nicht die Beschreibung und eine Beschreibung beinhaltet keine Aufgaben

Hinweis:
 -Hinweise können bei allen Überschriften dabei stehen. 
 -Hinweise müssen ebenfalls immer mit einem Bindestrich beginnen
 -Hinweise müssen immer mit einer Zeile Abstand unter den Gesichtspunkten einer Überschrift stehen
 -Hinweise sind nicht Pflicht und können weggelassen werden, sofern es keine gibt

**Kriterien für Abnahme:**
 -Kriterien haben ebenfalls immer mit einem Bindestrich zu beginnen
 -Kriterien werden vom Ersteller der Story/der Task festgelegt
 -Eine Story/ein Task ist erst abgeschlossen sobald die Kriterien erfüllt sind
 -Sofern es nicht klar ist muss beschrieben werden wie die Kriterien überprüft werden können

**Comment by Drumber** [comment]
### Vorschlag:
Man könnte die Aufgaben statt mit Bindestrichen mit den Checkboxen auflisten. Dadurch können die erledigten Aufgaben abgehakt werden, was zur Übersichtlichkeit/Transparenz des aktuellen Fortschritts beitragen kann.

### Beispiel:
- [x] Aufgabe 1...
- [ ] Aufgabe 2...
