### ISSUE TITLE
Task #68 - "Profil"-Icon und "Plus"-Icon anlegen

### ISSUE THREAD

**Issue by Lica200** [SE-TINF22B2/G4-Get2Gether#67]
### Beschreibung

Ich will administrative Aufgaben leicht durchführen können, der Einstieg zu diesen Aufgaben soll jedoch nicht zu viel Platz auf der Website einnehmen.
Ich will mit Hilfe des "Plus"-Icons([Design](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=43%3A217&mode=design&t=JkiIJnu4hdueUswh-1)) ein Event erstellen können.
Durch das Profilicon sollen administrative Aufgaben ausgeführt werden können. Durch das Hovern([Design](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=6%3A70&mode=design&t=JkiIJnu4hdueUswh-1)) über das Icon soll mein Name als Tooltip angezeigt werden. Beim Klicken auf mein Profilicon ([Design](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=6%3A255&mode=design&t=JkiIJnu4hdueUswh-1)), steht mir die Möglichkeiten zur Verfügung entweder zur Einstellungsmaske zu gelangen oder mich auszuloggen. Diese Knöpfe sollen zunächst im Frontend umgesetzt werden.

### Aufgaben

- [x] Die Icons ("Plus" und "Profil") werden entsprechend des [Designs in Figma](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=43%3A217&mode=design&t=JkiIJnu4hdueUswh-1) angezeigt
- [x] [Hovern](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=6%3A70&mode=design&t=JkiIJnu4hdueUswh-1) über das Profilicon zeigt den Namen entsprechend dem Design an
- [x] Das [Klicken auf mein Profilicon](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=6%3A255&mode=design&t=JkiIJnu4hdueUswh-1) zeigt ein Menü entsprechend dem Design

### Kriterien für die Abnahme

- Alle Aufgaben sind abgeschlossen

### Abgrenzkriterien
- Button-Funktionalitäten sollen noch nicht implementiert werden

**Comment by Drumber** [comment]
268110ebe514744375ab7de0ade0cd3e57da14ba

@ebauersandoval vielleicht können wir auch ein Plus Icon von Material Icons nehmen anstatt dem svg. Dann wären alle Icons konsistent und zudem kann die Farbe der Icons leichter geändert werden.
