### ISSUE TITLE
Task #73 - Eventübersicht und Eventbeschreibung anlegen

### ISSUE THREAD

**Issue by Lica200** [SE-TINF22B2/G4-Get2Gether#74]
### Beschreibung
Die Übersicht soll entsprechend der Figma-Vorlage erstellt werden, der Name, der Ort und die Zeit des Events sollen anzeigt 
 werden können. Außerdem sollen Bearbeiten und Löschen des Events visualisiert werden. Die Anzeige der Beschreibung des Events soll zudem möglich sein.

### Aufgaben

- [x] Card-Komponente mit Titel, Ort, Zeit, Hintergrund (farbig)
- [x] Card-Komponente für Beschreibung (ausklappbar)
- [x] Eventmenü (siehe zweiter Designlink) mit Aktionen "Bearbeiten" (ohne Funktionalität) und "Verlassen" 

### Designvorlagen
- [Eventseite](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=307%3A997&mode=design&t=QJ4jvbD6K5Uvq1U0-1)
- [Eventseite mit Eventmenü](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=307%3A2624&mode=design&t=QJ4jvbD6K5Uvq1U0-1)

**Comment by HaventSlept** [comment]
Die Farbzuteilung der Icons funktioniert noch nicht und muss überarbeitet werden. Die Bearbeitung der Story ist zwischen dem Branch von Sophia und mir aufgeteilt

**Comment by Drumber** [comment]
✅ Code-QA abgeschlossen und Änderungen gemerged!
