### ISSUE TITLE
Task #73 - Teilnehmerliste anlegen

### ISSUE THREAD

**Issue by Lica200** [SE-TINF22B2/G4-Get2Gether#76]
### Beschreibung
Über einen Link innerhalb der grundlegenden Eventinformationen sollen die Teilnehmer des Events in einer Seitenleiste angezeigt werden.

### Aufgaben
- [x] Link zur Seitenleiste
- [x] Seitenleiste mit Teilnehmerliste

### Designvorlagen
[Eventübersicht mit Teilnehmerliste](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=307%3A1069&mode=design&t=QJ4jvbD6K5Uvq1U0-1)

**Comment by Flugschnitzel** [comment]
Ausversehen bei der Commit Message #73 eingetragen

**Comment by Drumber** [comment]
✅ Code-QA abgeschlossen.

Sieht richtig gut aus, danke!
