### ISSUE TITLE
Task #82 - Logout Backend

### ISSUE THREAD

**Issue by Flugschnitzel** [SE-TINF22B2/G4-Get2Gether#81]
### Beschreibung

Wenn ein Nutzer sich im Frontend ausloggt, wird ein Request an das Backend gesendet. Bei Behandlung des Requests soll die Session gelöscht werden und der Nutzer auf die Login Seite weitergeleitet werden

### Aufgaben

- [ ] Endpunkt zum löschen der Session erstellt
- [ ] Weiterleitung auf Login Seite

### Kriterien für die Abnahme

- Session wird korrekt entfernt
- Nutzer wird korrekt weitergeleitet

**Comment by Drumber** [comment]
Spring Security provides a default logout endpoint that meets the requirements (see [here](https://docs.spring.io/spring-security/reference/servlet/authentication/logout.html).

I've changed the default logout redirect URL to `/` (main page) in cbc15e2.

For the frontend task, only a redirect to `http://<backend>/logout` is needed.
