### ISSUE TITLE
Task #84 - Event erstellen Frontend

### ISSUE THREAD

**Issue by sophiadeckhut** [SE-TINF22B2/G4-Get2Gether#86]
### Beschreibung

Bei Klick auf den "Plus"-Icon (vgl. #67) geht die Event erstellen Maske auf. Das aussehen basiert auf dem Design aus #85. In der Maske werden alle relevanten Information für ein neues Event eingetragen. Bei Klick auf "Speichern" wird mithilfe dieser Informationen ein neues Event im Backend angelegt und daraufhin der Seitenleiste angezeigt.

### Aufgaben

- [x] Bei Klick von "Plus"-Icon wird Event erstellen Maske angezeigt
- [x] Event erstellen Maske besitzt alle im Backend benötigten Felder entsprechend des Designs
- [x] Event erstellen Maske besitzt "Speichern" und "Abbrechen"-Button
- [x] Bei Klick auf "Speichern" werden Event-Daten an Backend geschickt
- [x] Bei Klick auf "Speichern" oder "Abbrechen" wird Maske geschlossen
- [x] Weiterleitung auf entsprechende Eventseite

### Kriterien für die Abnahme

- Anzeige funktioniert korrekt
- Felder funktionieren korrekt
- Buttons funktionieren korrekt
- Weiterleitung funktioniert korrekt

### Designvorlage
[Event-Maske Design](https://www.figma.com/file/DyyiQvYwesOsGv8rq9Qf5e/Final-Mockups?type=design&node-id=307%3A2368&mode=design&t=QJ4jvbD6K5Uvq1U0-1)

**Comment by Drumber** [comment]
✅ Code-QA abgeschlossen.

Sehr schön, danke dir!
