### ISSUE TITLE
Story #90 - Einkaufsliste Frontend Implementierung

### ISSUE THREAD

**Issue by Lica200** [SE-TINF22B2/G4-Get2Gether#90]
### Beschreibung

**Als** Nutzer **möchte** ich eine gemeinsame Einkaufsliste erstellen können, **um** somit Einkäufe besser zu organisieren. Dabei möchte ich die Möglichkeit haben einzelne Einträge hinzuzufügen, bei Bedarf diese nachträglich zu bearbeiten oder zu löschen. Der Eintrag soll eine Beschreibung, eine Menge und der Name des Ersteller. 

### Aufgaben

- [x] #127
- [x] #128
- [x] #129

### Kriterien für die Abnahme
- Das Widget Einkaufsliste ist erstellt und an verschiedene Bildschirmgrößen anpassbar.
- Die Umsetzung soll auf der Figme-Designvorlage basieren.
- Die Tasks #127, #128 und #129 sind abgeschlossen.

**Comment by Drumber** [comment]
✅ Code-QA abgeschlossen!
